[package]
license = "Apache-2.0"
edition = "2024"
name = "xtask"
version = "0.1.0"

[target.'cfg(any(windows, unix))'.dependencies]

anyhow = "1.0"
cargo_metadata = "0.23"
chrono = { version = "0.4", features = ["serde"] }
clap = {version = "4.4", features = ["derive"]}
colored = "3"
jkconfig = "0.1"
ostool = "0.8.4"
regex = "1.12"
reqwest = "0.13"
schemars = {version = "1", features = ["derive"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1"
sha2 = "0.10"
tokio = {version = "1", features = ["full"]}
toml.workspace = true

axvmconfig = {workspace = true, features = ["std"]}
tar = "0.4"
flate2 = "1.0"
