[package]
edition = "2024"
name = "axplat-aarch64-phytium-pi"
version = "0.1.0"

[dependencies]
axbsp-phytium-pi = {git = "https://github.com/drivercraft/axbsp.git", features = ["irq", "smp", "hv"]}

[build-dependencies]
serde = {version = "1.0", features = ["derive"]}
toml = "0.8"
