args = [
  "-nographic",
  "-cpu",
  "cortex-a72",
  "-machine",
  "virt,virtualization=on,gic-version=3",
  "-smp",
  "1",
  "-device",
  "virtio-blk-device,drive=disk0",
  "-drive", 
  "id=disk0,if=none,format=raw,file=${workspaceFolder}/tmp/rootfs.img",
  # "id=disk0,if=none,format=raw,file=/home/zhourui/arceos/axvisor-dev2/tmp/rootfs.img",
  "-m",
  "8g",
]
fail_regex = []
success_regex = []
to_bin = true
uefi = false
