args = [
  "-nographic",
  "-cpu",
  "max,sstc=on",
  "-machine",
  "virt,accel=tcg",
  "-bios",
  "default",
  "-smp",
  "4",
  "-device",
  "virtio-blk-device,drive=disk0",
  "-drive",
  "id=disk0,if=none,format=raw,file=${workspaceFolder}/tmp/rootfs.img",
  "-append",
  "root=/dev/vda rw init=/init",
  "-m",
  "8g",
]
fail_regex = []
success_regex = ["test pass!"]
to_bin = true
uefi = false
