[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "driver"
version.workspace = true

[features]
default = []
rk3568-clk = ["dep:rk3568_clk"]
rk3588-clk = ["dep:rk3588-clk"]
sdmmc = ["dep:sdmmc"]
rockchip-pm = ["dep:rockchip-pm"]
phytium-blk = ["dep:phytium-mci"]

[dependencies]
axklib.workspace = true
log.workspace = true
rdif-block = "0.6.2"
rdif-clk = "0.4"
rdrive.workspace = true
spin.workspace = true

rk3568_clk = { version = "0.1", optional = true }
sdmmc = { version = "0.1", default-features = false, features = ["pio"], optional = true }
rk3588-clk = { version = "0.1", optional = true }
rockchip-pm = { version = "0.4", optional = true }
phytium-mci = { version = "0.1", default-features = false, features = ["pio"], optional = true }