# Platform for Axvisor
plat = "aarch64-generic"
# Build features for Axvisor
features = ["ept-level-4"]
# Build arguments for ArceOS
arceos_args = ["BUS=mmio", "BLK=y", "MEM=8g", "LOG=debug", "QEMU_ARGS=\"-machine gic-version=3  -cpu cortex-a72  \""]
# ArceOS additional features
arceos_features = []

vmconfigs = []
