[package]
edition = "2024"
name = "axplat-x86-qemu-q35"
version = "0.1.0"

[features]
fp-simd = ["axplat-x86-pc/fp-simd"]
rtc = ["axplat-x86-pc/x86_rtc"]

[dependencies]
axplat-x86-pc = {git = "https://github.com/arceos-hypervisor/axplat_crates.git", branch="vmm", features = ["irq", "smp"]}
