# Vm base info configs
#
[base]
# Guest vm id.
id = 1
# Guest vm name.
name = "linux"
# Virtualization type.
vm_type = 1
# The number of virtual CPUs.
cpu_num = 8
# The physical CPU ids.
phys_cpu_ids = [0x00, 0x100, 0x200, 0x300, 0x400, 0x500, 0x600, 0x700]
# Guest vm physical cpu sets.
phys_cpu_sets = [1, 2, 4, 8, 16, 32, 64, 128]


#
# Vm kernel configs
#
[kernel]
# The entry point of the kernel image.
entry_point = 0x1_ce80_0000
# The location of image: "memory" | "fs".
# Load from memory.
image_location = "memory"
# The load address of the kernel image.
kernel_load_addr = 0x1_ce80_0000
## The file path of the kernel image.
kernel_path = "/path/to/kernel"
## The file path of the device tree blob (DTB).
dtb_load_addr = 0x1_cef0_0000
dtb_path = "/path/to/dtb"
# Memory regions with format (`base_paddr`, `size`, `flags`, `map_type`).
# For `map_type`, 0 means `MAP_ALLOC`, 1 means `MAP_IDENTICAL`.
memory_regions = [
  [0x1_ce80_0000, 0x2000_0000, 0x7, 1], # System RAM 1G MAP_IDENTICAL
  [0x8000_0000, 0x7000_0000, 0xf, 2],
]
#
# Device specifications
#
[devices]
# The interrupt mode.
interrupt_mode = "passthrough"
# Emu_devices.
# Name Base-Ipa Ipa_len Alloc-Irq Emu-Type EmuConfig.
emu_devices = []

# Pass-through devices.
# Name Base-Ipa Base-Pa Length Alloc-Irq.
passthrough_devices = [
["most-devices", 0x0, 0x0, 0x8000_0000, 0x1],
]

# Passthrough addresses.
# Base-GPA  Length.
passthrough_addresses = [
    #[0x28041000, 0x100_0000]
]

excluded_devices = [
   # ["/gic-v3"],
]