# Vm base info configs
#
[base]
# Guest vm id.
id = 2
# Guest vm name.
name = "linux"
# Virtualization type.
vm_type = 1
# The number of virtual CPUs.
cpu_num = 1
# The physical CPU ids.
# phys_cpu_ids = [0x00]

#
# Vm kernel configs
#
[kernel]
# The entry point of the kernel image.
# entry_point = 0x8008_0000
# The location of image: "memory" | "fs".
# Load from memory.
image_location = "fs"
# The load address of the kernel image.
# kernel_load_addr = 0x8008_0000
## The file path of the kernel image.
kernel_path = "/userdata/rootfs_overlay/guest/linux/roc-rk3568-pc"
## The file path of the device tree blob (DTB).
# dtb_load_addr = 0x8000_0000
#dtb_path = "/path/linux-aarch64-rk3568_smp1.dtb"
# Memory regions with format (`base_paddr`, `size`, `flags`, `map_type`).
# For `map_type`, 0 means `MAP_ALLOC`, 1 means `MAP_IDENTICAL`.
memory_regions = [
  [0x8000_0000, 0x6000_0000, 0x7, 1], # System RAM 1G MAP_IDENTICAL
]
#
# Device specifications
#
[devices]
# The interrupt mode.
interrupt_mode = "passthrough"
# Emu_devices.
# Name Base-Ipa Ipa_len Alloc-Irq Emu-Type EmuConfig.
emu_devices = []

# Pass-through devices.
# Name Base-Ipa Base-Pa Length Alloc-Irq.
passthrough_devices = [
    ["/"],
    #["/timer"],
]

# Passthrough addresses.
# Base-GPA  Length.
passthrough_addresses = [
    #[0x28041000, 0x100_0000]
]

# Devices that are not desired to be passed through to the guest
excluded_devices = [
   # ["/gic-v3"],
]
