# Vm base info configs
#
[base]
# Guest vm id.
id = 1
# Guest vm name.
name = "linux"
# Virtualization type.
vm_type = 1
# The number of virtual CPUs.
cpu_num = 1
# The physical CPU ids.
phys_cpu_ids = [0x100]
# Guest vm physical cpu sets.
phys_cpu_sets = [8]

#
# Vm kernel configs
#
[kernel]
# The entry point of the kernel image.
entry_point = 0x20_4008_0000
# The location of image: "memory" | "fs".
# Load from file system.
image_location = "fs"
# The load address of the kernel image.
kernel_load_addr = 0x20_4008_0000
## The file path of the kernel image.
kernel_path = "/guest/Image"
## The file path of the device tree blob (DTB).
dtb_path = "/guest/linux-aarch64-e2000_smp1.dtb"
dtb_load_addr = 0x20_4000_0000
# Memory regions with format (`base_paddr`, `size`, `flags`, `map_type`).
# For `map_type`, 0 means `MAP_ALLOC`, 1 means `MAP_IDENTICAL`.
memory_regions = [
    # [0x20_4000_0000, 0x4000_0000, 0x7, 1], # System RAM MAP_IDENTICAL
]

#
# Device specifications
#
[devices]
# Emu_devices.
# Name Base-Ipa Ipa_len Alloc-Irq Emu-Type EmuConfig.
emu_devices = []

# Pass-through devices.
# Name Base-Ipa Base-Pa Length Alloc-Irq.
passthrough_devices = [
    [
        "QSPI",
        0x0000_0000,
        0x0000_0000,
        0x1000_0000,
        0x1,
    ],
    [
        "LocalBus",
        0x1000_0000,
        0x1000_0000,
        0x1000_0000,
        0x1,
    ],
    [
        "low speed peripherals",
        0x2800_0000,
        0x2800_0000,
        0x0800_0000,
        0x1,
    ],
    [
        "other peripherals",
        0x3000_0000,
        0x3000_0000,
        0x0800_0000,
        0x1,
    ],
    [
        "IACC",
        0x3800_0000,
        0x3800_0000,
        0x0800_0000,
        0x1,
    ],
    [
        "PCIE",
        0x4000_0000,
        0x4000_0000,
        0x4000_0000,
        0x1,
    ],
    [
        "QSPI high address",
        0x01_0000_0000,
        0x01_0000_0000,
        0x8000_0000,
        0x1,
    ],
    [
        "LocalBus high address",
        0x01_8000_0000,
        0x01_8000_0000,
        0x8000_0000,
        0x1,
    ],
    [
        "PCIe MEM64",
        0x10_0000_0000,
        0x10_0000_0000,
        0x01_0000_0000,
        0x1,
    ],
]