cargo_args = []
features = [
  # "ept-level-4",
  "dyn-plat",
  "axstd/bus-mmio",
  "driver/sdmmc",
  "driver/rk3588-clk",
  "fs",
]
log = "Info"
target = "aarch64-unknown-none-softfloat"
to_bin = true
vm_configs = []
