cargo_args = []
features = [
    "dyn-plat",
    "axstd/bus-mmio",
    "fs",
    "driver/sdmmc",
    "driver/rk3568-clk"
]
log = "Info"
target = "aarch64-unknown-none-softfloat"
to_bin = true
vm_configs = []