args = [
  "-nographic",
  "-cpu",
  "cortex-a72",
  "-machine",
  "virt,virtualization=on,gic-version=3",
  "-smp",
  "1",
  "-append",
  "root=/dev/vda rw init=/init",
  "-m",
  "8g",
]
fail_regex = []
success_regex = []
to_bin = true
uefi = false
