args = [
  "-nographic",
  "-cpu",
  "rv64",
  "-machine",
  "virt",
  "-bios",
  "default",
  "-smp",
  "4",
  "-device",
  "virtio-blk-device,drive=disk0",
  "-drive",
  "id=disk0,if=none,format=raw,file=${workspaceFolder}/tmp/rootfs.img",
  "-m",
  "8g",
]
fail_regex = []
success_regex = [
    "Hello, world!",
    "test pass!",
]
to_bin = true
uefi = false