args = [
  "-nographic",
  "-cpu",
  "cortex-a72",
  "-machine",
  "virt,virtualization=on,gic-version=3",
  "-smp",
  "4",
  "-device",
  "virtio-blk-device,drive=disk0",
  "-drive",
  "id=disk0,if=none,format=raw,file=${workspaceFolder}/tmp/rootfs.img",
  "-append",
  "root=/dev/vda rw init=/init",
  "-m",
  "8g",
]
fail_regex = []
success_regex = [
    "Hello, world!",
    "test pass!",
]
to_bin = true
uefi = false
