baud_rate = "${env:BOARD_COMM_UART_BAUD}"
board_power_off_cmd = "${env:BOARD_POWER_OFF}"
board_reset_cmd = "${env:BOARD_POWER_RESET}"
dtb_file = "${env:BOARD_DTB}"
fail_regex = []
serial = "${env:BOARD_COMM_UART_DEV}"
success_regex = [
    "Welcome to AxVisor Shell!"
]

[net]
interface = "${env:BOARD_COMM_NET_IFACE}"
